---
- name: Install tooling from APT
  ansible.builtin.apt:
    name: "{{ dev_env_cpp_packages }}"
    state: present
    update_cache: true
  become: true
  when: ansible_facts["os_family"] == 'Debian'
